# Generated by Django 4.2.27 on 2026-01-13 05:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('debts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'عميل', 'verbose_name_plural': 'العملاء'},
        ),
        migrations.AlterModelOptions(
            name='debt',
            options={'verbose_name': 'دين', 'verbose_name_plural': 'الديون'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'عملية دفع', 'verbose_name_plural': 'المدفوعات'},
        ),
        migrations.AddField(
            model_name='customer',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم صاحب الحساب'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة'),
        ),
        migrations.AlterField(
            model_name='debt',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debts', to='debts.customer', verbose_name='العميل'),
        ),
        migrations.AlterField(
            model_name='debt',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='تاريخ الدين'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='debts.customer', verbose_name='العميل'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='تاريخ الدفع'),
        ),
    ]
