# Generated by Django 4.2.27 on 2026-01-13 11:37

import debts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='debt_duration_limit',
            field=models.IntegerField(default=30, verbose_name='مدة الدين المسموحة (أيام)'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=20, validators=[debts.models.validate_phone], verbose_name='رقم الهاتف (00218...)'),
        ),
        migrations.AlterField(
            model_name='debt',
            name='description',
            field=models.CharField(max_length=255, verbose_name='بيان الدين'),
        ),
    ]
